#!/bin/bash

MANIFEST=git://github.com/crdroidandroid/android.git
BRANCH=11.0
# ADDITIONAL_MANIFEST=
# ADDITIONAL_BRANCH=

function tg_sendText() {
curl -s "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
-d "parse_mode=html" \
-d text="${1}" \
-d chat_id=$CHAT_ID \
-d "disable_web_page_preview=true"
}

# Set up github's priviledged access
# mkdir -p ~/.ssh
# chmod 700 ~/.ssh
# echo "$id_rsa" > ~/.ssh/id_rsa
# echo "$id_rsa_pub" > ~/.ssh/id_rsa.pub
# chmod 400 ~/.ssh/id_rsa
git config --global user.email "$user_email"
git config --global user.name "$user_name"
# eval "$(ssh-agent -s)"
# ssh-add ~/.ssh/id_rsa
# echo "$known_hosts" > ~/.ssh/known_hosts


mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg_sendText "$send_shell" && sleep 2h
